# Python numpy 기초

## 2. 기본적인 색인 연산
[참고자료 링크](http://pinkwink.kr/716)

### Masking

In [1]:
import numpy as np
names = np.array (['Bob', 'Joe', 'Will', 'Bob', 'Will','Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='|S4')

In [8]:
dataNames = np.random.randn(7,4)
dataNames

array([[-0.47286312, -0.10456924,  0.56736959,  1.17081288],
       [ 1.05011387, -0.17249836, -1.93206164, -0.39676991],
       [ 1.60486038,  0.13839253,  0.88492272, -1.44186902],
       [-0.56649593,  0.25420123,  0.53930545,  1.38380079],
       [-0.18500001, -0.37920276, -1.02558201,  0.79261005],
       [ 0.48941475,  0.91281578, -0.07812885, -0.2519203 ],
       [ 0.53431112, -1.20693416, -0.63718115, -0.90684306]])

standard normal distribution    
[np.random.randn reference link](http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randn.html)

In [9]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [10]:
dataNames[names == 'Bob'] # 0번째 열, 3번째 열

array([[-0.47286312, -0.10456924,  0.56736959,  1.17081288],
       [-0.56649593,  0.25420123,  0.53930545,  1.38380079]])

In [15]:
dataNames[names == 'Bob', 2:]

array([[ 0.56736959,  1.17081288],
       [ 0.53930545,  1.38380079]])

In [16]:
dataNames[names == 'Bob', 2]

array([ 0.56736959,  0.53930545])

In [17]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [19]:
dataNames[~(names == 'Bob')] # 0번째 열, 3번째 열

array([[ 1.05011387, -0.17249836, -1.93206164, -0.39676991],
       [ 1.60486038,  0.13839253,  0.88492272, -1.44186902],
       [-0.18500001, -0.37920276, -1.02558201,  0.79261005],
       [ 0.48941475,  0.91281578, -0.07812885, -0.2519203 ],
       [ 0.53431112, -1.20693416, -0.63718115, -0.90684306]])

In [33]:
mask = (names is 'Bob') | (names is 'Will')
mask


False

In [34]:
mask = (names=='Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

#### is 와 == 의 차이점

[link](http://stackoverflow.com/questions/132988/is-there-a-difference-between-and-is-in-python)   

**==** is for value equality. Use it when you would like to know if two objects have the same value.   
   
   
**is** is for reference equality. Use it when you would like to know if two references refer to the same object.


In [35]:
dataNames[mask]

array([[-0.47286312, -0.10456924,  0.56736959,  1.17081288],
       [ 1.60486038,  0.13839253,  0.88492272, -1.44186902],
       [-0.56649593,  0.25420123,  0.53930545,  1.38380079],
       [-0.18500001, -0.37920276, -1.02558201,  0.79261005]])

In [37]:
dataNames[dataNames<0] = 0
dataNames

array([[ 0.        ,  0.        ,  0.56736959,  1.17081288],
       [ 1.05011387,  0.        ,  0.        ,  0.        ],
       [ 1.60486038,  0.13839253,  0.88492272,  0.        ],
       [ 0.        ,  0.25420123,  0.53930545,  1.38380079],
       [ 0.        ,  0.        ,  0.        ,  0.79261005],
       [ 0.48941475,  0.91281578,  0.        ,  0.        ],
       [ 0.53431112,  0.        ,  0.        ,  0.        ]])

In [39]:
dataNames[names != 'Joe'] = 7
dataNames

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 1.05011387,  0.        ,  0.        ,  0.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.48941475,  0.91281578,  0.        ,  0.        ],
       [ 0.53431112,  0.        ,  0.        ,  0.        ]])

### Simple Matrix Operations

In [40]:
dataMat = np.arange(15)
dataMat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [42]:
dataMat = dataMat.reshape((3,5))
dataMat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [43]:
dataMat.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [44]:
np.dot(dataMat, dataMat.T)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])