# Python numpy 기초

## 1. 기본 배열 선언과 간단한 연산
[참고자료 링크](http://pinkwink.kr/715)

In [1]:
import numpy as np

### Initializers 

In [5]:
np.ones((3,2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [6]:
np.zeros((3,2))

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [7]:
np.eye(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [9]:
data1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
data1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Data type

In [10]:
print(data1.shape, data1.dtype)

((3, 3), dtype('int64'))


In [11]:
float_data1 = data1.astype(np.float64)
float_data1

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [12]:
num_str = np.array(['1.25', '0.99', '44', '11'], dtype = np.string_)
num_str

array(['1.25', '0.99', '44', '11'], 
      dtype='|S4')

In [13]:
num_str.astype(float)

array([  1.25,   0.99,  44.  ,  11.  ])

### Operations

In [15]:
data1 * data1

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [16]:
data1 + 3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [31]:
print(data1 / 3)
print(float_data1 / 3)

print(data1 / 3.0)


[[0 0 1]
 [1 1 2]
 [2 2 3]]
[[ 0.33333333  0.66666667  1.        ]
 [ 1.33333333  1.66666667  2.        ]
 [ 2.33333333  2.66666667  3.        ]]
[[ 0.33333333  0.66666667  1.        ]
 [ 1.33333333  1.66666667  2.        ]
 [ 2.33333333  2.66666667  3.        ]]


In [30]:
print(data1 - data1/3)
print(float_data1 - float_data1/3)

print(data1 - data1/3.0)


[[1 2 2]
 [3 4 4]
 [5 6 6]]
[[ 0.66666667  1.33333333  2.        ]
 [ 2.66666667  3.33333333  4.        ]
 [ 4.66666667  5.33333333  6.        ]]
[[ 0.66666667  1.33333333  2.        ]
 [ 2.66666667  3.33333333  4.        ]
 [ 4.66666667  5.33333333  6.        ]]


In [29]:
print(1 / data1)
print(1 / float_data1)

print(1.0 / data1)


[[1 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1.          0.5         0.33333333]
 [ 0.25        0.2         0.16666667]
 [ 0.14285714  0.125       0.11111111]]
[[ 1.          0.5         0.33333333]
 [ 0.25        0.2         0.16666667]
 [ 0.14285714  0.125       0.11111111]]


In [28]:
data1 ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974],
       [ 2.64575131,  2.82842712,  3.        ]])

In [32]:
data1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

### Indexing 

In [34]:
data2 = np.arange(10)
data2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
data2[0]

0

In [36]:
data2[1:4]

array([1, 2, 3])

In [38]:
data2[1:4] = 10
data2

array([ 0, 10, 10, 10,  4,  5,  6,  7,  8,  9])

In [39]:
tmp = data2[1:4]
tmp[1] = 20
data2

array([ 0, 10, 20, 10,  4,  5,  6,  7,  8,  9])

In [40]:
data1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
data1[2]

array([7, 8, 9])

In [43]:
data1[2][0]

7

In [48]:
data1[2,0]
data1[2,0:1]


array([7])

In [49]:
data1[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
print(data1[:2,1:])
print(data1[:2][1:])

[[2 3]
 [5 6]]
[[4 5 6]]
